#!/bin/bash

set +x


arg=1;
while (( $arg < 100 )) ; do

	link='http://www.gettyimages.fr/photos/face?excludenudity=true&family=creative&page='
	link=$link$arg
	link=$link'&phrase=face&sort=best#license';

#	echo 'Valor de link: '$link;

	#read -r;

	wget -nd -N -H -k -E -p -R .1,js,html,css,svg -P ./positive -e robots=off $link
	
	(( arg = arg + 1 ));

#	echo "Valor de arg: $arg";
	#read -r;
done

exit

